name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Fly
        working-directory: frontend
        run: flyctl deploy --config=fly.toml --access-token=${{ secrets.FLY_API_KEY }}
